#!/bin/sh
#padsp julius-4.3.1 -input mic -demo -C  \/home\/erik\/Scrivania\/Progetto\/Progetto\/src\/speech_seed\/asr\/julian.jconf | grep --line-buffered "write file\|sentence1" > outf
padsp julius-4.3.1 -input mic -demo -C  \/home\/erik\/Scrivania\/Progetto\/Progetto\/src\/speech_seed\/asr\/julian.jconf > outf
